# Dockerfile References: https://docs.docker.com/engine/reference/builder/

# Start from the latest golang base image
FROM golang:latest as builder

RUN mkdir /app 
ADD . /app/ 
WORKDIR /app


RUN go get github.com/gorilla/mux
RUN go get gopkg.in/natefinch/lumberjack.v2
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o main .


FROM alpine:latest  

RUN apk --no-cache add ca-certificates

WORKDIR /root/

COPY --from=builder /app/main .

EXPOSE 8080

CMD ["./main"] 